import Head from "next/head";

import styles from "./index.module.scss";
import { Canvas } from "@react-three/fiber";
import { VideoPanel } from "../components/videoPanel";
import YouTubeVideo from "../components/youtubeVideo";

export default function Home() {
  return (
    <>
      <Head>
        <title>website.mov</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.body}>
          <YouTubeVideo />
        </div>
        <h1 className={styles.title}>david.mov</h1>
      </main>
    </>
  );
}
